version: '3.8'

services:

  # Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network
  

  # Kafka UI
  kafka-ui:
    container_name: kafkaInterface
    image: provectuslabs/kafka-ui:latest  # Considere especificar uma versão
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - app-network


  # Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  # Microserviço 1 - m1sevicepayament
  m1sevicepayament:
    container_name: m1sevicepayament
    build:
      context: ./m1sevicepayament
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - KAFKA_BROKER=kafka:9092

  # Microserviço 2 - m2sevicenotification
  m2sevicenotification:
    container_name: m2sevicenotification
    build:
      context: ./m2sevicenotification
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - m1sevicepayament
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=payments
      - CONSUMER_GROUP_ID=notification_group

networks:
  app-network:
    driver: bridge
