# Usando uma imagem base do OpenJDK 17
FROM openjdk:17-jdk-alpine

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando o arquivo JAR gerado para dentro da imagem Docker
COPY target/paymentmicroservico-0.0.1-SNAPSHOT.jar app.jar

# Definindo o comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]

# Expondo a porta usada pelo Spring Boot
EXPOSE 8080
